// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOPLziJ2YRVOuA8o7aOSmO3q7iu_EFqtk',
    appId: '1:1097085823729:web:6218965f1ee8801f5a1750',
    messagingSenderId: '1097085823729',
    projectId: 'e-commerce-appp',
    authDomain: 'e-commerce-appp.firebaseapp.com',
    storageBucket: 'e-commerce-appp.appspot.com',
    measurementId: 'G-G5F7SCTWBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDERwNTVD2L6M3CEDTjUOzwtVxWISFZV1o',
    appId: '1:1097085823729:android:554c9baaa08cfdfd5a1750',
    messagingSenderId: '1097085823729',
    projectId: 'e-commerce-appp',
    storageBucket: 'e-commerce-appp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvLMJRrb3wlCdMopXI-DyeopDlVSvAslo',
    appId: '1:1097085823729:ios:1b333b6fed4443395a1750',
    messagingSenderId: '1097085823729',
    projectId: 'e-commerce-appp',
    storageBucket: 'e-commerce-appp.appspot.com',
    iosClientId: '1097085823729-pn0fnlul936br6rn7qd9l0tk14tb1gk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvLMJRrb3wlCdMopXI-DyeopDlVSvAslo',
    appId: '1:1097085823729:ios:1b333b6fed4443395a1750',
    messagingSenderId: '1097085823729',
    projectId: 'e-commerce-appp',
    storageBucket: 'e-commerce-appp.appspot.com',
    iosClientId: '1097085823729-pn0fnlul936br6rn7qd9l0tk14tb1gk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
